version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler
          command: bundle -v
      - run: sudo apt-get install --only-upgrade sqlite3 libsqlite3-dev
      - run: sqlite3 --version
      - ruby/bundle-install
      - run: bundle exec rake
      - run: bundle exec codeclimate-test-reporter
